### ISSUE TITLE
unconvert doesn't support vendoring

### ISSUE THREAD

**Issue by stevenh** [mdempsky/unconvert#19]
If you try to use unconvert on code which has vendored dependencies it reports bogus errors

For example:
```
main.go:6:2:warning: could not import github.com/pkg/errors (cannot find package "github.com/pkg/errors" in any of: (unconvert)
main.go:11:14:warning: undeclared name: errors (unconvert)
```
Where main.go clearly imports errors:
```go
package main

import (
        "fmt"

        "github.com/pkg/errors"
)

func main() {
        err := fmt.Errorf("some error")
        fmt.Println(errors.Wrap(err, "my wrapped error"))
}
```

To ensure you get this error you need github.com/pkg/errors vendored and it must NOT be in your GOPATH.

Also reported to gometalinter:  https://github.com/alecthomas/gometalinter/issues/190

**Comment by dnephin** [comment]
I have been using `unconvert` on multiple repos , all of which have vendored packages, and none of those packages are installed to the goroot. This might be an issue in your environment.

**Comment by stevenh** [comment]
All other metalinters work so we’ve got no evidence to support this being an environment issue

**Comment by DenisNeustroev** [comment]
the same

**Comment by mdempsky** [comment]
unconvert doesn't do any import path resolution itself. This is handled by x/tools/go/loader, which I think just uses go/build. I'm not even aware of how unconvert could participate in this path resolution process if it wanted to.

@stevenh In opennota/check#33, you said reported that this was fixed for aligncheck. Do you know what was changed there to fix the issue?

**Comment by mdempsky** [comment]
I'm going to optimistically close this. If there's any problems with vendor support, it's a bug in `x/tools/go/packages`.
