### ISSUE TITLE
Is this a bug, a false positive, or a gap in my understanding?

### ISSUE THREAD

**Issue by metaleap** [mdempsky/unconvert#22]
For [watcher-default.go#L45](https://github.com/metaleap/go-util-fs/blob/master/watcher-default.go#L45), `unconvert -v github.com/metaleap/go-util-fs` reports:

    /home/me/c/go/src/github.com/metaleap/go-util-fs/watcher-default.go:45:33: unnecessary conversion
            me.DebounceNano = time.Duration(250 * time.Millisecond).Nanoseconds()
                                           ^

I don't see *any* conversions anywhere near?!

Same result with `-safe`, except prepended by line:

    ... huh, *ast.SelectorExpr at /home/me/c/go/src/github.com/metaleap/go-util-fs/watcher-default.go:45:20

**Comment by shurcooL** [comment]
> I don't see _any_ conversions anywhere near?!

I believe there is an unnecessary conversion of `250 * time.Millisecond`, which has type `time.Duration`, to `time.Duration`, right here:

```Go
time.Duration(250 * time.Millisecond)
```

The conversion can be removed, simplifying that line to:

```Go
me.DebounceNano = (250 * time.Millisecond).Nanoseconds()
```

See [playground sample](https://play.golang.org/p/MaxZt7bsV5).

**Comment by metaleap** [comment]
Ahh! That would be it I guess! I assumed (for no good reason) that this tool would only look for `foo.(bar)` syntax

**Comment by cznic** [comment]
> I assumed (for no good reason) that this tool would only look for foo.(bar) syntax

But that's not a conversion.

**Comment by metaleap** [comment]
Eeeek, excuse me guys for being slow and mixing up terms after some 4+ years outside golang land 😁
