### ISSUE TITLE
C: no such file or directory

### ISSUE THREAD

**Issue by xlab** [mdempsky/unconvert#23]
```
$ unconvert -v github.com/vulkan-go/vulkan
2017/07/07 16:17:49 open /Users/xlab/Documents/dev/go/src/github.com/vulkan-go/vulkan/C: no such file or directory
```

```
go version go1.9beta2 darwin/amd64
```

**Comment by shurcooL** [comment]
Does anything change if you do `go install -v github.com/vulkan-go/vulkan`, and then by `unconvert -v github.com/vulkan-go/vulkan`?

**Comment by xlab** [comment]
@shurcooL I tried, it doesn't help.
```
$ go install -v github.com/vulkan-go/vulkan
github.com/vulkan-go/vulkan
$ unconvert -v github.com/vulkan-go/vulkan
2017/07/07 18:07:56 open /Users/xlab/Documents/dev/go/src/github.com/vulkan-go/vulkan/C: no such file or directory
```

**Comment by cznic** [comment]
It looks like some loader mistakenly attempts to `import "C"`.

**Comment by xlab** [comment]
@cznic @shurcooL I actually tried to create a minimal reproducible, but it works fine in handmade cases..

**Comment by mdempsky** [comment]
Minimal repro case:

    package p
    
    // unsigned int myfunc();
    import "C"
    
    func f() interface{} {
    	return C.myfunc
    }

The "C" file is actually the _cgo_gotypes.go file generated by cgo. The "C" name is synthesized by go/loader.

**Comment by mdempsky** [comment]
Looks like this is working now to me: `unconvert -v github.com/vulkan-go/vulkan` prints a bunch of unnecessary conversions.
