### ISSUE TITLE
Potential false positives in Go 1.9 due to new syntax to force intermediate rounding of floating point operations.

### ISSUE THREAD

**Issue by shurcooL** [mdempsky/unconvert#24]
@mdempsky, a new language change in Go 1.9 is described as:

> A smaller language change is that the language specification now states when implementations are allowed to fuse floating point operations together, such as by using an architecture's "fused multiply and add" (FMA) instruction to compute x\*y + z without rounding the intermediate result x\*y. To force the intermediate rounding, write float64(x\*y) + z.

If I understand correctly, that means in Go 1.9, the following two snippets have different behavior:

```Go
var a, b, c float64 = 1.2, 3.4, 5.6
x := (a * b) + c
```

```Go
var a, b, c float64 = 1.2, 3.4, 5.6
x := float64(a * b) + c // Force intermediate rounding in Go 1.9.
```

However, `unconvert` would simplify the second block to the first, which would change behavior.

Is my understanding correct?

**Comment by shurcooL** [comment]
It seems this was mentioned/discussed at https://github.com/golang/go/issues/17895#issuecomment-293417087.

**Comment by mdempsky** [comment]
Correct, in visitor.unconvert there should be a check that if ft.Type's underlying type is float32/float64/complex64/complex128, then the conversion needs to be kept.

At least by default. I suppose we could add a -fma=false flag or something to restore historical behavior.
