### ISSUE TITLE
tests aren't checked

### ISSUE THREAD

**Issue by tamird** [mdempsky/unconvert#25]
Seems that the call to [`(*golang.org/x/tools/go/loader.Config).Import`](https://godoc.org/golang.org/x/tools/go/loader#Config.Import) should be [`(*golang.org/x/tools/go/loader.Config).ImportWithTests`](https://godoc.org/golang.org/x/tools/go/loader#Config.ImportWithTests) instead.

**Comment by shurcooL** [comment]
If support for tests is added, it would be nice to make it a boolean flag that's default true, similar to other tools, e.g.:

https://github.com/dominikh/go-tools/blob/b0e79018b59e45680f7b4eee178fabe79ac5e794/lint/lintutil/util.go#L120

(/cc @dominikh FYI, link to your code.)

**Comment by mdempsky** [comment]
A `-test` flag seems reasonable to me.
