### ISSUE TITLE
Make ... syntax work for packages

### ISSUE THREAD

**Issue by cespare** [mdempsky/unconvert#4]
Thanks for the great tool! It would be nice if you could do e.g. `unconvert ./...` to check a tree of packages at once.

**Comment by mdempsky** [comment]
Is `...` expansion something commonly supported by other similar tools? I know x/tools/cmd/eg doesn't.

I've been using

    unconvert `go list ./...`

**Comment by dominikh** [comment]
errcheck supports it (by using github.com/kisielk/gotool, which is extracted from the Go tool), golint supports it (haven't checked how), guru now supports it (by using its own implementation in buildutil which allows negations, but doesn't understand "std" or "all")

**Comment by mdempsky** [comment]
Okay, sounds like unconvert should support it too then.

**Comment by shurcooL** [comment]
gostatus [supports it](https://github.com/shurcooL/gostatus/blob/e400277c2abf67c6ccc69d6d24f55f7bb0749492/main.go#L89-L90) (by using github.com/kisielk/gotool), goimporters [supports it](https://github.com/shurcooL/cmd/blob/44f2307d09fe119d163fc3b027a26df3e22d7c15/goimporters/main.go#L45-L50) (by using github.com/kisielk/gotool and `resolveRelative`), and goimportgraph [supports it](https://github.com/shurcooL/cmd/blob/master/goimportgraph/main.go#L51-L59) (by using github.com/kisielk/gotool and `resolveRelative`).

I think it's great for Go tools to support import path patterns, I consider them an excellent feature of Go. If a tool says it accepts [packages] but doesn't allow import path patterns, it's unfortunate.

Also, github.com/kisielk/gotool makes it very easy to do so, so there's no reason not to.

**Comment by mdempsky** [comment]
I was originally hesitant to add non-stdlib dependencies, but I see now that github.com/kisielk/gotool is pretty trivial and self-contained.  If someone wants to upload a PR to make use of it, I'll review it.  (Same offer goes for mdempsky/maligned#4.)

**Comment by shurcooL** [comment]
Yep, it's basically original stdlib code but made exported, so it can be reused by 3rd party tools.

I'll make that PR tonight if no one beats me to it.

**Comment by shurcooL** [comment]
Made #9.
