### ISSUE TITLE
no arguments should mean . (again)

### ISSUE THREAD

**Issue by dmitshur** [mdempsky/unconvert#44]
This is a bug that was reported previously as #8, and was fixed in #9, but regressed in #32.

`unconvert` without arguments should be the same as `unconvert .`, that is operate on the Go package in the current working directory.

This is the cause:

https://github.com/mdempsky/unconvert/blob/2f5dc3378ed3ba283f5125b8bb47f6ba672f879b/unconvert.go#L221-L224

Before #32 was applied, that code looked like this:

https://github.com/mdempsky/unconvert/blob/dc69f12fff3087ab405d3c0759549bb7a1dcfd3b/unconvert.go#L200-L203

The difference is that `gotool.ImportPaths([]string(nil))` returned `[]string{"."}`. This isn't the case after #32 replaced that with just `flag.Args()`.

Note that `packages.Load(cfg)` returns the same result as `packages.Load(cfg, ".")`, it loads the package in the current working directory. The current code just never reaches the call to `packages.Load`.

/cc @egonelbre @mvdan

P.S. I noticed this because of https://github.com/shurcooL/octicon/blob/9ff1a4cf27f4a918862c3ffbd24371b3aed18f9d/doc.go#L10.

**Comment by mvdan** [comment]
If this is fixed once again, consider adding a test via https://godoc.org/github.com/rogpeppe/go-internal/testscript. Otherwise one of these edge cases is bound to be broken in the future again :)

**Comment by dmitshur** [comment]
Another alternative is [`golang.org/x/tools/go/packages/packagestest`](https://godoc.org/golang.org/x/tools/go/packages/packagestest).

**Comment by mdempsky** [comment]
PRs to add proper testing are welcome. :)
