### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by slnt** [mdempsky/unconvert#46]
`unconvert` doesn't show up nicely in a `go.mod` (eg: `github.com/mdempsky/unconvert v0.0.0-20190921185256-3ecd357795af`)

Since its been stable for quite a while, tag a v1.0.0 release?

**Comment by slnt** [comment]
@mdempsky thoughts?

**Comment by mvdan** [comment]
Is there a problem with the lack of releases, though? Pseudo-versions are pretty normal in Go modules. Committing to a v1 also means committing to stability, which I'm not sure is a good idea just yet.

**Comment by mdempsky** [comment]
@mvdan I'm happy to delegate to you and @dmitshur on this. Unconvert exists originally because of a need to cleanup the Go runtime after translating it from C to Go. I personally haven't used it since then.

**Comment by mvdan** [comment]
I'm going to close this for now, then. I don't oppose releases per se, but I also don't think there is any benefit or rush to doing a v1.0.0.
