### ISSUE TITLE
Tag v0.0.1

### ISSUE THREAD

**Issue by mcandre** [mdempsky/unconvert#60]
Can we please get some version tags pushed, to help pin this tool to a specific version?

As a workaround, users could cite a particular commit hash, but that's not as convenient as a version git tag.

**Comment by mvdan** [comment]
Personally I don't see the reason to - once you start tagging, you also have to tag regularly, otherwise "latest" lags behind. The tool works fine, and using a commit works too. See https://github.com/mdempsky/unconvert/issues/46.

**Comment by mcandre** [comment]
Commit hashes as versions, DevOps favorite meal.
