### ISSUE TITLE
No args should mean .

### ISSUE THREAD

**Issue by mvdan** [mdempsky/unconvert#8]
Same as https://github.com/mdempsky/maligned/issues/4.

**Comment by shurcooL** [comment]
I agree. I think this is a duplicate of #4 though, which @mdempsky [agreed with on March 14th](https://github.com/mdempsky/unconvert/issues/4#issuecomment-196463717). This is a subset of that issue, I think.

It's worth asking if a PR would be helpful.

**Comment by mvdan** [comment]
Oh, true. I didn't notice that issue was about `gotool` when looking through the issues. Not technically a duplicate, but fixing that one will fix this one too.
